server:
  port: ${PORT:8080}
  tomcat:
    threads:
      max: 200
  ssl:
    trust-store: /Users/asaify/Documents/my-workspace/chat-bot/src/main/resources/truststore.jks
    trust-store-password: changeit
    enabled: false

spring:
  application:
    name: chatbot-bot-backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:chat_bot}
    username: asaify
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true


security:
  api-keys: ${API_KEYS:dev-key-123} # comma-separated raw keys for demo
  rate-limit-per-minute: ${RATE_LIMIT_PER_MIN:120}

rag:
  embedding:
    provider: ${EMBEDDING_PROVIDER:stub} # stub|openai
    model: ${EMBEDDING_MODEL:text-embedding-3-small}
    openai-api-key: ${OPENAI_API_KEY:}
    dimension: ${EMBEDDING_DIM:384}
  retrieval:
    top-k: ${RETRIEVAL_TOP_K:3}
  generation:
    provider: ${LLM_PROVIDER:anthropic} # stub|openai|anthropic|gemini
    openai:
      model: ${OPENAI_MODEL:gpt-4o-mini}
      api-key: ${OPENAI_API_KEY:}
    anthropic:
      model: ${ANTHROPIC_MODEL:claude-3-5-sonnet-20240620}
      api-key: ${ANTHROPIC_API_KEY:}
      base-url:
    gemini:
      model: ${GEMINI_MODEL:gemini-1.5-pro}
      api-key: ${GEMINI_API_KEY:}
