server:
  port: ${PORT:8080}
  tomcat:
    threads:
      max: 200
    max-connections: 8192
    connection-timeout: 20000
    max-http-form-post-size: 100MB
    max-swallow-size: 100MB
  ssl:
    trust-store: /Users/asaify/Documents/my-workspace/chat-bot/src/main/resources/truststore.jks
    trust-store-password: changeit
    enabled: false

spring:
  application:
    name: chatbot-bot-backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:chat_bot}
    username: asaify
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true


security:
  api-keys: dev-key-123
  rate-limit-per-minute: 120

rag:
  embedding:
    model: bge-m3
    api-key:
    base-url: 
    batch-size: 5
  chunking:
    default-type: fixed-size
    default-chunk-size: 800
    default-overlap-size: 80
    max-chunks-per-document: 5000
  storage:
    batch-size: 10
  pipeline:
    thread-pool-size: 4
    max-document-size: 100MB
    memory-optimization: true
  retrieval:
    top-k: 3
llm:
  generation:
    provider: anthropic # stub|openai|anthropic|gemini
    anthropic:
      model: qwen25-coder-32b
      api-key:
      base-url:
    gemini:
      model: gemini-1.5-pro
      api-key:
      base-url:

#  gemini-2.0-flash-lite
#  gemini-2.0-flash
#  gemini-2.5-pro-preview-03-25
#  gpt-4.1
#  gpt-4o-mini
#  gpt-4o
#  claude-3-7-sonnet-20250219
#  claude-3-5-haiku-20241022
#  llama33-70b
#  llama31-8b
#  deepseek-r1-distill-llama-70b
#  deepseek-r1-distill-qwen-32b
#  qwen25-coder-32b