server:
  port: ${PORT:8080}
  tomcat:
    threads:
      max: 200
  ssl:
    trust-store: /Users/asaify/Documents/my-workspace/chat-bot/src/main/resources/truststore.jks
    trust-store-password: changeit
    enabled: false

spring:
  application:
    name: chatbot-bot-backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:chat_bot}
    username: asaify
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true


security:
  api-keys: dev-key-123 # comma-separated raw keys for demo
  rate-limit-per-minute: 120

rag:
  embedding:
    provider: stub # stub|openai
    model: text-embedding-3-small
  retrieval:
    top-k: 3
  generation:
    provider: anthropic # stub|openai|anthropic|gemini
    openai:
      model: gpt-4o-mini
      api-key:
    anthropic:
      model: gpt-4o
      api-key:
      base-url: 
    gemini:
      model: gemini-1.5-pro
      api-key: AIzaSyBnA91rE0yGrBTysGl_di-tgXiizzvQg3U
      base-url: https://generativelanguage.googleapis.com

#  gemini-2.0-flash-lite
#  gemini-2.0-flash
#  gemini-2.5-pro-preview-03-25
#  gpt-4.1
#  gpt-4o-mini
#  gpt-4o
#  claude-3-7-sonnet-20250219
#  claude-3-5-haiku-20241022
#  llama33-70b
#  llama31-8b
#  deepseek-r1-distill-llama-70b
#  deepseek-r1-distill-qwen-32b
#  qwen25-coder-32b